export const CONNECT_ORDERS = "CONNECT_ORDERS";
export const CONNECT_ORDERS_SUCCESS = "CONNECT_ORDERS_SUCCESS";
export const LOAD_ORDERS = "LOAD_ORDERS";
export const ADD_ORDERS = "ADD_ORDERS";
export const LOAD_ORDERS_ERROR = "LOAD_ORDERS_ERROR";

export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_LOAD_DATA = "SOCKET_LOAD_DATA";
export const SOCKET_ADD_DATA = "SOCKET_ADD_DATA";
export const SOCKET_ERROR = "SOCKET_ERROR";
export const SOCKET_RECONNECT = "SOCKET_RECONNECT";
